@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NDM3YjAwOWNjYjY2MjdkNmQ0YzhjNyIsImlhdCI6MTY5ODkyMTQ5MywiZXhwIjoxNzAxNTEzNDkzfQ.mzyYpzPbeSHZ0tyilYMKIEXd3sZnJ1KzR2xJvHm3Xkw
@tokenuser = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NDM3Yzk3NzNkMzYzZDQwMjkzOTdkOSIsImlhdCI6MTY5ODkyMTY0NywiZXhwIjoxNzAxNTEzNjQ3fQ.1vcK_X1xegrYjudjRgACeGnfhJjk0T1GCxwB6hAxsK0
@userid = 65437c9773d363d4029397d9

POST http://localhost:3001/api/v1/users
Content-Type: application/json
Authorization: {{token}}

{
  "name": "user",
  "password": "111111",
  "email": "user@gmail.com",
  "role": "user"
}

###

POST http://localhost:3001/api/v1/auth/login
Content-Type: application/json

{
  "password": "111111",
  "email": "user@gmail.com",
  "email2": "ahmad.furqon@gmail.com"
}

###
GET http://localhost:3001/api/v1/users
Content-Type: application/json
Authorization: {{token}}

###
GET http://localhost:3001/api/v1/users/{{userid}}
Content-Type: application/json
Authorization: {{token}}